# Generated by Django 3.0.3 on 2020-02-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_booklist'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='author',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name'), name='unique_author'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('author', 'title', 'first_published'), name='unique_book'),
        ),
        migrations.AddConstraint(
            model_name='booklist',
            constraint=models.UniqueConstraint(fields=('user', 'book'), name='unique_booklist'),
        ),
    ]
