# Generated by Django 3.0.3 on 2020-02-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200215_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='override_cover',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
